### ISSUE TITLE
Usage section from the ReadMe is not working

### ISSUE THREAD

**Issue by fmros** [uf-reef-avl/BagGetFilter#1]
There is no file indicated by the usage section
```
./BagGetFilter...

**Comment by solnirv** [comment]
Hi, 
In the README, there is download link in blue. You will have to extract the zip file and use the executable command line ./BagGetFilter... on the extracted file. I will setup a release or update the readme

**Comment by fmros** [comment]
ok got it, i would highlight the download link in the usage section
